[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Films"
  pageRef = "films"
  weight = 20

[[main]]
  name = "Contact"
  pageRef = "contact"
  weight = 30

[[main]]
  name = "Cinsiders"
  pageRef = "cinsiders"
  weight = 40
